git: pre-commit hook

diff --git a/.config/git/template/hooks/pre-commit b/.config/git/template/hooks/pre-commit
--- a/.config/git/template/hooks/pre-commit
+++ b/.config/git/template/hooks/pre-commit
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 if [ -z "$(git config --local user.name)" ] || [ -z "$(git config --local user.email)" ]; then
-	echo "Error: You must set a local user.name and user.email before committing."
-	echo "Use git.config user.name \"Your Name\" and git config user.email \"Your E-Mail\"."
-	exit 1
+  echo "Error: You must set a local user.name and user.email before committing."
+  echo "Use git config user.name \"Your Name\" and git config user.email \"Your E-Mail\"."
+  exit 1
 fi
-# vim:ft=sh
